openapi: 3.0.1
info:
  title: '@jupiterone/graph-databricks'
  description: A JupiterOne Integration for ingesting data for the Databricks
  x-cortex-git:
    github:
      repository: JupiterOne/graph-databricks
  x-cortex-owners:
    - type: group
      name: JupiterOne/integrations
  x-cortex-tag: '@jupiterone/graph-databricks'
  x-cortex-service-groups:
    - tier-4
